### ISSUE TITLE
Option? Top drawer just hide.

### ISSUE THREAD

**Issue by artelse** [krisbalintona/org-hide-drawers#2]
Testing the package to replace `org-tidy`. It works as expected, but I do like how `org-tidy` just hides the top property drawer without an indicator. Can this be added?

**Comment by krisbalintona** [comment]
> Testing the package to replace `org-tidy`. It works as expected, but I do like how `org-tidy` just hides the top property drawer without an indicator. Can this be added? 

For sure. I can work on it soon.

Thinking about it now, I'll probably adjust the `org-hide-drawers-display-string` option such that users can set different display strings based on user-defined conditions. The idea being that the user can have the display string for the top drawer be nil and it'll automatically make the overlay invisible --- or something like that. Just a first thought though; I might choose a different route when I get to it.

Also, as a future note, the internals of this package are designed to cover all of the features org-tidy did and then some. Though the feature parity isn't quite there yet, it's just a matter of taking the time to implement those features. My general approach is to wait and see what users want/need before adding features --- so thanks for chiming in :)

>Edit: I also would like the drawer to be open when toggled because that is what one wants mostly.

I don't think I understand you correctly. Do you just mean that you want the top drawer to be un-hidden when disabling `org-hide-drawers-mode`?

**Comment by artelse** [comment]
Cool, good suggestion on the nil string for the top drawer. About the second issue, I just think it is nice when a header drawer is revealed it is opened and not closed, so one doesn't need two actions.

**Comment by artelse** [comment]
The second issue of the drawer being closed when revealed can be solved by setting `org-cycle-hide-drawer-startup` to `nil`. However this only works for header drawers not buffer ones, because this is part of `org-cycle` I suppose. Don't know if there is a setting for the top drawer somewhere.

**Comment by okomestudio** [comment]
> Thinking about it now, I'll probably adjust the `org-hide-drawers-display-string` option such that users can set different display strings based on user-defined conditions. The idea being that the user can have the display string for the top drawer be nil and it'll automatically make the overlay invisible --- or something like that. Just a first thought though; I might choose a different route when I get to it.

I came in to check if a ticket already exists for this. Instead of creating a separate ticket, please allow me to add my comment here.

I would like to have separate custom variables for `display-string` on the file-level property drawer and the header-level property drawer. 

It's not just having separate control, but also using different strings. The display string for the file-level property drawer is aligned to the left edge of the buffer, whereas for the header-level property drawer it is appended to an existing header text. I want to insert a white space before each display string for header-level property drawer, but not for the file-level property drawer. I cannot currently do something like this.

**Comment by krisbalintona** [comment]
> > Thinking about it now, I'll probably adjust the `org-hide-drawers-display-string` option such that users can set different display strings based on user-defined conditions. The idea being that the user can have the display string for the top drawer be nil and it'll automatically make the overlay invisible --- or something like that. Just a first thought though; I might choose a different route when I get to it.
> 
> I came in to check if a ticket already exists for this. Instead of creating a separate ticket, please allow me to add my comment here.
> 
> I would like to have separate custom variables for `display-string` on the file-level property drawer and the header-level property drawer.
> 
> It's not just having separate control, but also using different strings. The display string for the file-level property drawer is aligned to the left edge of the buffer, whereas for the header-level property drawer it is appended to an existing header text. I want to insert a white space before each display string for header-level property drawer, but not for the file-level property drawer. I cannot currently do something like this.

Hi,

I agree. It was always in my vision for the package to support such cases. I just hadn't gotten to it yet since at the time the package had not even landed on MELPA; I had just implemented my specific preferences. (I actually want the exact same behavior you desrcibe, but it never bothered me enough to implement.) But I designed the package to easily support such cases. The only question is the UX (i.e. options) for such a feature.

I want to avoid having a plethora of options. Instead, I'd like to figure out a way to have a single option that controls the display strings the user wants for any type of drawer. I've thought about having a syntax like `buffer-match-p` where the option is a list of conses whose car is a special symbol denoting the kind of drawer and whose cdr is the display string for that drawer. Additionally, we can have a special symbol specifically for user-defined cases: the cdr could be a unary function that takes in the drawer and returns the desired display string. This way, I think all use cases are neatly covered in a single option.

How does that sound? I hope the above reads well; I just wanted to type up something rough-and-ready. If nothing about it seems unwise, I'll try implementing it this weekend.

**Comment by krisbalintona** [comment]
> Thanks for offering the devel branch. Unfortunately, the code throws an error at this line:
> 
> https://github.com/krisbalintona/org-hide-drawers/blob/devel/org-hide-drawers.el#L197
> 
> since `org-hide-drawers--set-display-strings-func` is used before the function is defined.

@okomestudio Oops... should be fixed now.

**Comment by okomestudio** [comment]
It now seems to work for me, but I think that the `:set` function is not correctly written in a way to properly set and bind `org-hide-drawers-display-strings` on update. After setting a custom value via `setopt`, it cannot be accessed as Emacs Lips thinks it's unbound.

**Comment by krisbalintona** [comment]
I'll look into it soon. Everything looks good on my end, even setting it by `setopt`.

**Comment by krisbalintona** [comment]
> Testing the devel branch. I don't get an error, but fontification in org-mode gets fucked up somehow. I use a hook to load it on org-mode. Edit: fucked up doesn't seem helpful ;) I mean it looses all font colors, etc.

Hmmm, do you mind showing a backtrace if possible? Also could you share what you've set `org-hide-drawers-display-strings` to?

**Comment by krisbalintona** [comment]
> It now seems to work for me, but I think that the `:set` function is not correctly written in a way to properly set and bind `org-hide-drawers-display-strings` on update. After setting a custom value via `setopt`, it cannot be accessed as Emacs Lips thinks it's unbound.

Ah, thanks for pointing that out. Looks like I misread the manual. Should be fixed in the latest commit on that branch.

Although, it actually shouldn't have effected the functionality, since `org-hide-drawers-display-strings` isn't actually referenced anywhere. It's `org-hide-drawers--display-strings-func` which is set when `org-hide-drawers-display-strings` is set (via :set) that's referenced.

**Comment by okomestudio** [comment]
> I'll look into it soon. Everything looks good on my end, even setting it by `setopt`.

Just to clarify what I mean, the way to reproduce the issue for me is (1) load the org-hide-drawers feature; (2) use `(setopt org-hide-drawers-display-strings ...)` to customize the strings; (3) visit an Org document while it is activated; (4) try to see the value/documentation for `org-hide-drawers-display-strings` with `describe-variable`/`helpful-variable`. I get `void-variable` error with debug on, and its preview (in helpful-variable completion) says `#<unbound>`.

**Comment by krisbalintona** [comment]
> > I'll look into it soon. Everything looks good on my end, even setting it by `setopt`.
> 
> Just to clarify what I mean, the way to reproduce the issue for me is (1) load the org-hide-drawers feature; (2) use `(setopt org-hide-drawers-display-strings ...)` to customize the strings; (3) visit an Org document while it is activated; (4) try to see the value/documentation for `org-hide-drawers-display-strings` with `describe-variable`/`helpful-variable`. I get `void-variable` error with debug on, and its preview (in helpful-variable completion) says `#<unbound>`.

Looks like we replied at the same time: https://github.com/krisbalintona/org-hide-drawers/issues/2#issuecomment-2971605340.

**Comment by krisbalintona** [comment]
> Cannot get it to work properly. This error appears when an org file is loaded:
> `File mode specification error: (void-function org-hide-drawers--set-display-strings-func)`
> 
> This is my minimal config:
> ```
>   (use-package org-hide-drawers
>     :vc (:url "https://github.com/krisbalintona/org-hide-drawers" :branch "devel")
>     :ensure t
>     :diminish
>     :hook (org-mode . org-hide-drawers-mode)
>     :custom
>     (org-hide-drawers-hide-top-level-properties-drawer t))
> ```

I think you might be using a commit before I fixed that problem. Do you mind pulling again and reporting back?

**Comment by artelse** [comment]
With the latest commit I still get errors and loss of fontification. When I open an org file it now reports:
`File mode specification error: (void-function nil)`
And the persistent `*scratch*` org buffer:
`Failed to restore scratch buffers: (void-function truncate-string-ellipsis)`

This could be related to my config, but don't know really how to debug this properly.

**Comment by krisbalintona** [comment]
@artelse I think I've figured it out. If I'm right, it looks like there was something in my own configuration that was hiding the problem (and package-lint wasn't telling me about it).

**Comment by krisbalintona** [comment]
> That error seems to be fixed. When I open an org file I simply get this error: `File mode specification error: (void-function nil)` And fontification still lost. Edit: when I `Reload Org (after update)` and followed by `Refresh setup current buffer`, fontification is back and the top properties drawer shows `[Hidden...]` I can then also toggle the drawer on and off.

Hm, so does everything seem good only after you reload org (and by that do you mean `org-mode-restart`?)?

I think it'd be helpful if you enable debugging on error (i.e. `toggle-debug-on-error`) and paste the backtrace shown after the error here. There seems to be a call to a function "nil" (where nil is obviously not a function) and I'd like to see the backtrace so I can see what precisely goes wrong and whether org-hide-drawers has something to do with it.

**Comment by artelse** [comment]
Ok, this fixes the loading problem. However, the org hook to enable `org-hide-drawers-mode` doesn't work, I have to manually call it. For me it would be helpful if you provide a couple of config examples to for example set the display string and how to completely hide the top drawer. I appreciate the design philosophy to be max flexible, but from a users pov with simple needs it becomes a bit unwieldy.

**Comment by krisbalintona** [comment]
> Ok, this fixes the loading problem. However, the org hook to enable `org-hide-drawers-mode` doesn't work, I have to manually call it. 

Can you confirm this with an emacs -q? (You can also use `package-isolate` and select org-hide-drawers if you're in a new enough Emacs version.) On my end, with my personal configuration and emacs -q, it works fine.

For instance, this shows expected behavior on my end:
```emacs-lisp
(use-package org-hide-drawers
    :ensure nil ; Assuming the devel branch of org-hide-drawers is already in load-path
    :defer t
    :hook (org-mode . org-hide-drawers-mode))
```
If you don't have `package-isolate`, you can test it with something like this in the CLI:
```
emacs -q -L "/path/to/org-hide-drawers-directory/" --eval "(progn
                            (use-package org-hide-drawers :ensure nil :defer t :hook (org-mode . org-hide-drawers-mode)) (find-file \"/path/to/org-file.org\"))"
```

> For me it would be helpful if you provide a couple of config examples to for example set the display string and how to completely hide the top drawer. I appreciate the design philosophy to be max flexible, but from a users pov with simple needs it becomes a bit unwieldy.

Do the examples in the docstring of `org-hide-drawers-display-strings` not suffice? I think it'd be a good idea to include a few starter configurations in the README for visibility, but the docstring of that user option should be more comprehensive while still providing a few demonstrative examples.

And thank you for the feedback. Let me know if you have any other gripes or wishes related to the purpose of the new user option; it'll be useful to hear any other opinions you (or anyone else) may have before merging into main.
